title: "Predicting if an individual is diabetic from health factor"
author: "Angela Chen, Ella Hein, Scout McKee, Sharon Voon."
date: "2023-12-01"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force 
bibtex_bibfiles:
    - references.bib